accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from accounts import views

urlpatterns = [
        url(r'^login$', views.persona_login, name='persona_login'),
        url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls
from accounts import urls as account_urls


urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(account_urls)),
]

accounts/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'


    def is_authenticated(self):
        return True

lists/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

class List(models.Model):

    @property
    def name(self):
        first_text = self.item_set.first().text.split(" ")
        return " ".join(first_text[0:5]) + "..."
    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):

    def __str__(self):
        return self.text 

    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError
from lists.models import Item


EMPTY_ITEM_ERROR = "A wise man once said nothing at all. I'll go ahead and not add that to the list..."
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):
    
    class Meta:
        
        model = Item
        fields = ('text',)
        widgets = {
                'text': forms.fields.TextInput(attrs={
                    'placeholder': 'Add your quote here...',
                    'class': 'form-control input-lg',
                    }),
        }
        error_messages = {
                'text': {'required': EMPTY_ITEM_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()


class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    
    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    
    def save(self):
        return forms.models.ModelForm.save(self)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

import sys

# Create your views here.

def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
    return HttpResponse('OK')

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect,render
from django.http import HttpResponse
from django.contrib.auth import get_user_model
User = get_user_model()

from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item, List

# Create your views here.
def home_page(request): 
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List()
        if request.user.is_authenticated():
            list_.owner = request.user
        list_.save()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form":form})

def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Quotable</title>
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/bootstrap/bootflat/css/bootflat.css" rel="stylesheet">
        <link href="/static/bootstrap/css/site.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>

    <body>

        <nav class="navbar navbar-quotable" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <div style="position:relative"><a class="navbar-brand quotable-header-link quotable-logo" href="/">Quotable</a></div>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.email %}
                            <li>
                            <a class="nav-link quotable-header-link" href="{%url 'my_lists' user.email %}">My Lists</a>
                            </li>
                            <li>
                            <a class="nav-link quotable-header-link" href="/">New List</a>
                            </li>

                            <li>
                            <a class="nav-link quotable-header-link" href="#" id="id_logout">Logout</a>
                            </li>
                            <li>
                              <span class="nav-link quotable-header-link logged-in">Logged in as {{user.email}}</span>
                            </li>

                        {% else %}
                            <li>
                            <a class="nav-link quotable-header-link" href="#" id="id_login">Sign In</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">

            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        {% block list_form %}
                        <form method="POST" action="{% block form_action %}{% endblock %}">
                            {{ form.text }}
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                            {% endif %}
                        </form>
                        {% endblock %}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block extra_content %}
                    {% endblock %}
                </div>
            </div>
        </div>

        <div class="row navbar-fixed-bottom">
            <div class="col-md-12">
                <div class="footer">
                    <div class="container">
                        <div class="clearfix">
                            <div class="footer-logo col-md-3"><a class="quotemark" href="#">Quotable</a></div>
                            <div class="col-md-9">
                                <p class="quotable-footer-text"> Quotable is a minimalist app for collecting and sharing quotes with friends. </p>
                                <p class="quotable-footer-text"> I'm created it while working through Harry Percival's excellent book "Test-driven Development with Python".</p>
                                <p class="quotable-footer-text"> You are welcome to create an account to use the app, of course. Keep in mind the goal of this project was to learn about a different way of doing things while familiarizing myself with some new back-end, deployment / configuration management, continuous integration and authentication tools (<a href="https://www.djangoproject.com" target="_blank">Django</a>, <a href="http://www.fabfile.org" target="_blank">Fabric</a>, <a href="https://jenkins-ci.org" target="_blank" >Jenkins</a> and <a href="https://www.mozilla.org/en-US/persona/"> Persona </a> specifically) - not to create a featureful app with an award-winning front end! :) </p>
                                <p class="quotable-footer-text"> Lists are grouped with your account, but are not private. Don't add anything you wouldn't want to share publicly!</p>
                            </div>
                        </div>
                        <div class="footer-copyright text-center" style="margin-top: 2em"><a href="https://github.com/ragle/tdd-with-django">See the code on github</a> - <a href="http://staging.quotable.site">upstream (staging) server</a> - <a href="http://jenkins.quotable.site/view/Quotable/">Jenkins dash</a> - <a href="https://ragle.sanukcode.net">ragle@sanukcode</a></div>
                    </div>
                </div>
            </div>
        </div>

        <script src="http://code.jquery.com/jquery.min.js"></script>
        <script src="https://login.persona.org/include.js"></script>
        <script src="/static/accounts.js"></script>
        <script src="/static/list.js"></script>
        <script>
            $(document).ready(function () {
                var user = "{{ user.email }}" || null;
                var token = "{{ csrf_token }}";
                var urls = {
                    login: "{% url 'persona_login' %}",
                    logout: "{% url 'logout' %}",
                };
                Superlists.Accounts.initialize(navigator, user, token, urls);
            });
        </script>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %} Start a new list of Quotes {% endblock%}
{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %} Your Quotes {% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
  <table id="id_list_table" class="table">
      {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
      {% endfor %}
  </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
  <h4>{{ owner.email}}'s lists</h4>
  <ul>
      {% for list in owner.list_set.all %}
        <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
      {% endfor %}
  </ul>
{% endblock %}